# Generated by Django 3.0.8 on 2020-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200713_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
